services:
  mysql:
    image: mysql:8.0
    container_name: omni-assistant-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: omni_assistant
      MYSQL_USER: omni_user
      MYSQL_PASSWORD: omni_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - omni-network

volumes:
  mysql_data:
    driver: local

networks:
  omni-network:
    driver: bridge
