spring:
  application:
    name: omni-assistant
  
  datasource:
    url: jdbc:mysql://localhost:3307/omni_assistant?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# Add frontend configuration
frontend:
  url: ${FRONTEND_URL}

logging:
  level:
    org.assistant: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.assistant.config: DEBUG
